title: Felipe Sánchez Nájera
logo: /docs/assets/images/Foto_FSN_OIM.jpg
description: Data analyst and human rights expert with more than seven years of experience in the design, implementation, and evaluation of data based projects (including the collection, cleaning, analysis, visualization/communication, and modeling/forecasting of data) regarding various human rights issues.
#show_downloads: true
theme: jekyll-theme-minimal
