title: Felipe Sánchez Nájera
logo: /docs/assets/images/Foto_FSN_OIM.jpg
description: Data analyst and human rights expert with more than seven years of experience in the design, implementation, and evaluation of data based projects (including the collection, cleaning, analysis, visualization/communication, and modeling/forecasting of data) regarding various human rights issues.
#show_downloads: true
  <br><br>
  <a href="www.linkedin.com/in/felipe-sanchez-najera/">View My LinkedIn Profile</a> 
  <br><br>
theme: jekyll-theme-minimal
